//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace PCS.Report.XSD {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsPrincipalCardTypeAllowed : DataSet {
        
        private _TableDataTable table_Table;
        
        public dsPrincipalCardTypeAllowed() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsPrincipalCardTypeAllowed(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Table"] != null)) {
                    this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public _TableDataTable _Table {
            get {
                return this.table_Table;
            }
        }
        
        public override DataSet Clone() {
            dsPrincipalCardTypeAllowed cln = ((dsPrincipalCardTypeAllowed)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Table"] != null)) {
                this.Tables.Add(new _TableDataTable(ds.Tables["Table"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.table_Table = ((_TableDataTable)(this.Tables["Table"]));
            if ((this.table_Table != null)) {
                this.table_Table.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsPrincipalCardTypeAllowed";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsPrincipalCardTypeAllowed.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.table_Table = new _TableDataTable();
            this.Tables.Add(this.table_Table);
        }
        
        private bool ShouldSerialize_Table() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void _TableRowChangeEventHandler(object sender, _TableRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPCTAID;
            
            private DataColumn columnpctaCDCTID;
            
            private DataColumn columncdctCode;
            
            private DataColumn columnctaRemarks;
            
            private DataColumn columnDateCreated;
            
            private DataColumn columnCreatedBy;
            
            private DataColumn columnLastUpdated;
            
            private DataColumn columnUpdatedBy;
            
            internal _TableDataTable() : 
                    base("Table") {
                this.InitClass();
            }
            
            internal _TableDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PCTAIDColumn {
                get {
                    return this.columnPCTAID;
                }
            }
            
            internal DataColumn pctaCDCTIDColumn {
                get {
                    return this.columnpctaCDCTID;
                }
            }
            
            internal DataColumn cdctCodeColumn {
                get {
                    return this.columncdctCode;
                }
            }
            
            internal DataColumn ctaRemarksColumn {
                get {
                    return this.columnctaRemarks;
                }
            }
            
            internal DataColumn DateCreatedColumn {
                get {
                    return this.columnDateCreated;
                }
            }
            
            internal DataColumn CreatedByColumn {
                get {
                    return this.columnCreatedBy;
                }
            }
            
            internal DataColumn LastUpdatedColumn {
                get {
                    return this.columnLastUpdated;
                }
            }
            
            internal DataColumn UpdatedByColumn {
                get {
                    return this.columnUpdatedBy;
                }
            }
            
            public _TableRow this[int index] {
                get {
                    return ((_TableRow)(this.Rows[index]));
                }
            }
            
            public event _TableRowChangeEventHandler _TableRowChanged;
            
            public event _TableRowChangeEventHandler _TableRowChanging;
            
            public event _TableRowChangeEventHandler _TableRowDeleted;
            
            public event _TableRowChangeEventHandler _TableRowDeleting;
            
            public void Add_TableRow(_TableRow row) {
                this.Rows.Add(row);
            }
            
            public _TableRow Add_TableRow(long PCTAID, long pctaCDCTID, string cdctCode, string ctaRemarks, System.DateTime DateCreated, string CreatedBy, System.DateTime LastUpdated, string UpdatedBy) {
                _TableRow row_TableRow = ((_TableRow)(this.NewRow()));
                row_TableRow.ItemArray = new object[] {
                        PCTAID,
                        pctaCDCTID,
                        cdctCode,
                        ctaRemarks,
                        DateCreated,
                        CreatedBy,
                        LastUpdated,
                        UpdatedBy};
                this.Rows.Add(row_TableRow);
                return row_TableRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                _TableDataTable cln = ((_TableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new _TableDataTable();
            }
            
            internal void InitVars() {
                this.columnPCTAID = this.Columns["PCTAID"];
                this.columnpctaCDCTID = this.Columns["pctaCDCTID"];
                this.columncdctCode = this.Columns["cdctCode"];
                this.columnctaRemarks = this.Columns["ctaRemarks"];
                this.columnDateCreated = this.Columns["DateCreated"];
                this.columnCreatedBy = this.Columns["CreatedBy"];
                this.columnLastUpdated = this.Columns["LastUpdated"];
                this.columnUpdatedBy = this.Columns["UpdatedBy"];
            }
            
            private void InitClass() {
                this.columnPCTAID = new DataColumn("PCTAID", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPCTAID);
                this.columnpctaCDCTID = new DataColumn("pctaCDCTID", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpctaCDCTID);
                this.columncdctCode = new DataColumn("cdctCode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncdctCode);
                this.columnctaRemarks = new DataColumn("ctaRemarks", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnctaRemarks);
                this.columnDateCreated = new DataColumn("DateCreated", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDateCreated);
                this.columnCreatedBy = new DataColumn("CreatedBy", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCreatedBy);
                this.columnLastUpdated = new DataColumn("LastUpdated", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLastUpdated);
                this.columnUpdatedBy = new DataColumn("UpdatedBy", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUpdatedBy);
            }
            
            public _TableRow New_TableRow() {
                return ((_TableRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new _TableRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(_TableRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this._TableRowChanged != null)) {
                    this._TableRowChanged(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this._TableRowChanging != null)) {
                    this._TableRowChanging(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this._TableRowDeleted != null)) {
                    this._TableRowDeleted(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this._TableRowDeleting != null)) {
                    this._TableRowDeleting(this, new _TableRowChangeEvent(((_TableRow)(e.Row)), e.Action));
                }
            }
            
            public void Remove_TableRow(_TableRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRow : DataRow {
            
            private _TableDataTable table_Table;
            
            internal _TableRow(DataRowBuilder rb) : 
                    base(rb) {
                this.table_Table = ((_TableDataTable)(this.Table));
            }
            
            public long PCTAID {
                get {
                    try {
                        return ((long)(this[this.table_Table.PCTAIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.PCTAIDColumn] = value;
                }
            }
            
            public long pctaCDCTID {
                get {
                    try {
                        return ((long)(this[this.table_Table.pctaCDCTIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.pctaCDCTIDColumn] = value;
                }
            }
            
            public string cdctCode {
                get {
                    try {
                        return ((string)(this[this.table_Table.cdctCodeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.cdctCodeColumn] = value;
                }
            }
            
            public string ctaRemarks {
                get {
                    try {
                        return ((string)(this[this.table_Table.ctaRemarksColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.ctaRemarksColumn] = value;
                }
            }
            
            public System.DateTime DateCreated {
                get {
                    try {
                        return ((System.DateTime)(this[this.table_Table.DateCreatedColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.DateCreatedColumn] = value;
                }
            }
            
            public string CreatedBy {
                get {
                    try {
                        return ((string)(this[this.table_Table.CreatedByColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.CreatedByColumn] = value;
                }
            }
            
            public System.DateTime LastUpdated {
                get {
                    try {
                        return ((System.DateTime)(this[this.table_Table.LastUpdatedColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.LastUpdatedColumn] = value;
                }
            }
            
            public string UpdatedBy {
                get {
                    try {
                        return ((string)(this[this.table_Table.UpdatedByColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.table_Table.UpdatedByColumn] = value;
                }
            }
            
            public bool IsPCTAIDNull() {
                return this.IsNull(this.table_Table.PCTAIDColumn);
            }
            
            public void SetPCTAIDNull() {
                this[this.table_Table.PCTAIDColumn] = System.Convert.DBNull;
            }
            
            public bool IspctaCDCTIDNull() {
                return this.IsNull(this.table_Table.pctaCDCTIDColumn);
            }
            
            public void SetpctaCDCTIDNull() {
                this[this.table_Table.pctaCDCTIDColumn] = System.Convert.DBNull;
            }
            
            public bool IscdctCodeNull() {
                return this.IsNull(this.table_Table.cdctCodeColumn);
            }
            
            public void SetcdctCodeNull() {
                this[this.table_Table.cdctCodeColumn] = System.Convert.DBNull;
            }
            
            public bool IsctaRemarksNull() {
                return this.IsNull(this.table_Table.ctaRemarksColumn);
            }
            
            public void SetctaRemarksNull() {
                this[this.table_Table.ctaRemarksColumn] = System.Convert.DBNull;
            }
            
            public bool IsDateCreatedNull() {
                return this.IsNull(this.table_Table.DateCreatedColumn);
            }
            
            public void SetDateCreatedNull() {
                this[this.table_Table.DateCreatedColumn] = System.Convert.DBNull;
            }
            
            public bool IsCreatedByNull() {
                return this.IsNull(this.table_Table.CreatedByColumn);
            }
            
            public void SetCreatedByNull() {
                this[this.table_Table.CreatedByColumn] = System.Convert.DBNull;
            }
            
            public bool IsLastUpdatedNull() {
                return this.IsNull(this.table_Table.LastUpdatedColumn);
            }
            
            public void SetLastUpdatedNull() {
                this[this.table_Table.LastUpdatedColumn] = System.Convert.DBNull;
            }
            
            public bool IsUpdatedByNull() {
                return this.IsNull(this.table_Table.UpdatedByColumn);
            }
            
            public void SetUpdatedByNull() {
                this[this.table_Table.UpdatedByColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class _TableRowChangeEvent : EventArgs {
            
            private _TableRow eventRow;
            
            private DataRowAction eventAction;
            
            public _TableRowChangeEvent(_TableRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public _TableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
